[package]
name = "rsynth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = { version = "0.13.4", features = ["jack"] }
anyhow = "1.0.12"
pitch_calc = "0.12.0"
lockfree = "0.5.1"
fltk = "^1.2"